# Generated by Django 5.2.5 on 2026-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='roll_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
